mirror docker images
kubernetes-sigs/kind pull request #2105
Opened 2021-03-04 09:56 UTC by aojea

Kind is publishing the official in dockerhub, however, since
the docker decision to rate limit the images, this causes issues
with CIs.

Switching completely the images is complicated, and can be very
disruptive.

Meanwhile we don't have a final decision we can mirror the images
to different public registries.

Fixes: https://github.com/kubernetes-sigs/kind/issues/1895

2021-03-04 09:58 UTC, aojea commented
/hold
/assign @BenTheElder 
Open for discussion, this still needs to handle the authentication
- I was thinking in using a dns domain to hide the registries, so we can geodistribute the requests and we no longer depend on the registry provider.
- Is this the right repo or do we want to use github.com/kind-ci as we do with the containerd nigthly builds
- ....

2021-03-04 09:59 UTC, aojea commented on .github/workflows/mirror.yml
> +  release:
this runs when a release is created

2021-03-04 09:59 UTC, aojea commented on .github/workflows/mirror.yml
> +          skopeo sync --src docker --dest docker docker.io/kindest/node ghcr.io/kind-ci
not familiar with the feature but if it handles the sync ala rsync that seems exactly what we need

2021-03-04 13:22 UTC, neolit123 reviewed
LGTM

2021-03-04 15:54 UTC, tao12345666333 commented
The authentication information can be completed through the configuration of `--dest-authfile` and `--src-authfile` combined with [GitHub Action encrypted-secrets](https://docs.github.com/en/actions/reference/encrypted-secrets).

Docker Inc. provides support for open source projects, we can consider using it. https://www.docker.com/community/open-source/application

2021-03-05 06:32 UTC, AkihiroSuda commented on .github/workflows/mirror.yml
> +          skopeo sync --src docker --dest docker docker.io/kindest/node ghcr.io/kind-ci
End users will want this mirrored image as well :+1:, so maybe `-ci` suffix can be omitted.

2021-03-05 13:02 UTC, BenTheElder requested changes
I'm NACK on mirroring to random registries here without deciding on the solution over in the issue.

Any mirroring we run from here is "official" and should be decided and supported. Also because dockerd has poor support for mirrors we should really just pick 1-2 registries to use going forward (maybe k8s official GCR and something else for china, unless we can pick one alternative for both), and mirroring solutions should be done in discussion with wg-k8s-infra.

2021-03-05 13:22 UTC, aojea commented on .github/workflows/mirror.yml
> +          skopeo sync --src docker --dest docker docker.io/kindest/node quay.io/kind
I made up the names, the pr is to discuss if this make sense.
If affirmative fill the gaps with whatever we decide

2021-03-11 07:37 UTC, BenTheElder commented
[thanks for the PR, let's continue discussion elsewhere, closing to minimize issues from #2120 / thundering CI on open PRs with ok-to-test]

[also received contact from docker today about kindest, need to follow up with them]

2021-03-11 07:37 UTC, closed without merging