reload containerd on config changes
kubernetes-sigs/kind pull request #2274
Opened 2021-05-24 15:50 UTC by aojea

We are doing the same on the image preloading, 
do we need to be gentle with containerd :) ?

Fixes: https://github.com/kubernetes-sigs/kind/issues/2262

2021-05-24 22:01 UTC, BenTheElder requested changes
the way we're doing image loading is considered a bug to fix.
we should not mimic it here. the tools are available to do this correctly.

2021-05-24 22:33 UTC, aojea commented
TIL `systemctl is-system-running --wait`

2021-05-25 08:34 UTC, aojea commented
/retest

2021-05-25 10:01 UTC, aojea commented
fedora images seems to not be available
```

URL: ["https://vagrantcloud.com/fedora/33-cloud-base"]
Error: The requested URL returned error: 403
Bringing machine 'default' up with 'virtualbox' provider..
```

2021-05-25 12:46 UTC, AkihiroSuda commented
> @AkihiroSuda should we switch to fedora34?

I have a PR to switch the default to 34: https://github.com/kubernetes-sigs/kind/pull/2220
But depends on https://github.com/kubernetes-sigs/kind/pull/2230.

Opened https://github.com/kubernetes-sigs/kind/pull/2279 as an attempt to deflake 33.

2021-07-22 22:54 UTC, BenTheElder commented on pkg/cluster/internal/create/actions/config/config.go
> +				// wait until boot has finished
we want to only restart it if we observed it was already running after completing the patching, if it wasn't running waiting and restarting it is:
a) slow
b) unnecessary (as it never read the old unpatched config)

there's still a race as to wether or not it starts before we check to restart it, but if we check to restart it and it wasn't running we're fine and if it was running we restart it and wether or not it read the old config it's fine and we don't waste much time.

the problem previously is an ineffective check for it it is running.

2021-07-22 23:20 UTC, BenTheElder commented
filed https://github.com/kubernetes-sigs/kind/pull/2382 https://github.com/kubernetes-sigs/kind/pull/2274#discussion_r675212707

2021-07-23 05:56 UTC, closed without merging

2021-07-23 05:56 UTC, aojea commented
Duplicate